### ISSUE TITLE
Article detail vs. huge Search

### ISSUE THREAD

**Issue by Majkl578** [chemix/planette#2]
It's weird to have a huge Search area when the user lands on the page with an article.

Also, it feels strange that the search box has autofocus - it's fine on homepage, but not here (e.g. it's impossible to Space to _scroll_ unless you unselect the box).

**Comment by paveljanda** [comment]
Agree with the huge search input.
Also i would keep the list of all articles/tutorials/... on planette homepage, maybe sorted by stars/hearts/whatever.

**Comment by chemix** [comment]
@Majkl578 fixed
@paveljanda homepage has little update too
