### ISSUE TITLE
Buttons flow over search results and other elements

### ISSUE THREAD

**Issue by paveljanda** [chemix/planette#3]
<img width="916" alt="screen shot 2015-07-28 at 08 57 37" src="https://cloud.githubusercontent.com/assets/1488874/8925286/d6d4e984-3506-11e5-8fe8-cf24c01734f6.png">

**Comment by paveljanda** [comment]
<img width="949" alt="screen shot 2015-07-28 at 08 59 04" src="https://cloud.githubusercontent.com/assets/1488874/8925301/f4d1b3cc-3506-11e5-94e1-3868db9afb72.png">

**Comment by chemix** [comment]
Now, it's using css from nette.org (.wiki navigation) and I have in a plan change this design

@paveljanda Some idea where to place this "navigation"

**Comment by paveljanda** [comment]
Well, i would put the Language "toggler" simply to the header or footer, because all user are used to do so there.

And the Profile/Action buttons to the [header](http://getbootstrap.com/components/#navbar) - again, because users are ussed to.
